# SPDX-License-Identifier: MIT-0
---
# vars file for roles/env_init
env_init_mark_dir_path: /root/.marks
env_init_mark_file_path: "{{ env_init_mark_dir_path }}/init_env_success.mark"

env_init_hosts_path: /etc/hosts

env_init_packages:
  - dnf-plugins-core
  - python3-pip
  - vim
  - git
  - wget
  - epel-release
  - centos-release-openstack-dalmatian

env_init_openstack_client_package: python3-openstackclient

env_init_ntp_template_src: chrony.conf.j2
env_init_ntp_conf_path: /etc/chrony.conf

env_init_ntp_server: "ntp.aliyun.com"
