# SPDX-License-Identifier: MIT
galaxy_info:
  author: lraltas
  description: Install and configure Memcached (caching service used by OpenStack)
  company: XWStudio

  # License for this role (SPDX identifier)
  license: MIT

  min_ansible_version: '2.9'

  galaxy_tags:
    - openstack
    - memcached

dependencies: []
