# SPDX-License-Identifier: MIT
galaxy_info:
  author: lraltas
  description: Install and configure Glance (OpenStack Image service)
  company: XWStudio
  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  # License for this role (SPDX identifier)
  license: MIT

  min_ansible_version: '2.9'

  galaxy_tags:
    - openstack
    - glance

dependencies: []
